// Crucible C++ driver — shared body for BOTH C++ corelibs:
//   cpp    -> corelib-cpp        (pure C++20, header-only)
//   c-cpp  -> corelib-c-cpp      (the C++ wrapper over the C corelib)
//
// build.sh selects which `sofab/sofab.hpp` is on the include path; the generated
// probe.hpp and the sofab:: API (IStreamObject, Result, Error) are identical
// across both, so this one source builds against either.
//
// Single pass: the generated Probe::try_decode fills the value and RETURNS the
// Result (verdict) in one call — and, on the pure-corelib-cpp measure-then-deliver
// decoder, installs the §5.2 measure-phase schema (generator#216) a bare feed omits.
//
// Emits the canonical form (oracle/canonical.md) over the replay protocol
// (drivers/common/CONTRACT.md).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include "probe.hpp" // generated; pulls the variant's sofab/sofab.hpp

// Materialized-value walker (oracle/materialized.md), SOFAB_MATERIALIZE=1. GENERATED
// at build time from the schema descriptor by materialize_gen.py (build.sh runs it
// before this compile); a schema change regenerates it with zero hand-editing. It
// provides `std::string materialize(const message::Probe&)`, unrolled straight-line
// member-access code written against ONLY the member API shared by both corelib
// variants (std::string/std::vector/std::array vs FixedString/FixedBytes/InlineVector),
// so this one source stays variant-agnostic. See materialize_gen.py.
#include "materialize_gen.inc" // generated by build.sh -> gen/$VARIANT/

static const char *reject_class(sofab::Error e)
{
    switch (e)
    {
        case sofab::Error::InvalidMessage:  return "invalid_msg";
        case sofab::Error::InvalidArgument: return "argument";
        case sofab::Error::UsageError:      return "usage";
        case sofab::Error::BufferFull:      return "buffer_full";
        default:                            return "other";
    }
}

static void decode_and_report(const std::uint8_t *data, std::size_t len, FILE *out)
{
    message::Probe m; // schema defaults

    // An empty buffer is the valid all-defaults message. The c-cpp wrapper routes
    // to the C istream, which asserts datalen>0 as a debug precondition (see the C
    // driver / docs/ARCHITECTURE.md), so skip feed for len==0 as the C driver does.
    if (len > 0)
    {
        // Go through the GENERATED try_decode, not a bare IStreamObject::feed: on
        // the pure-corelib-cpp measure-then-deliver decoder it installs the
        // measure-phase schema (setSchema, generator#216) that rejects an over-count
        // / over-maxlen / over-index field at its deciding word, so a field that is
        // BOTH over-bound and truncated is INVALID (§5.2), not INCOMPLETE. A bare
        // feed never installs that schema, so it reported INCOMPLETE (F-0032). It
        // fills `m` on ok and returns the same Result as feed; on c-cpp it is a
        // straight feed (the fixed-capacity wrapper needs no measure schema).
        auto r = message::Probe::try_decode(data, len, m);
        if (r.incomplete())
        {
            // INCOMPLETE (MESSAGE_SPEC §7): bytes end mid-message — the third
            // canonical verdict, neither accept (A) nor reject (R). Not an error.
            std::fputs("I\n", out);
            return;
        }
        if (!r.ok())
        {
#ifdef CRUCIBLE_HAS_LIMIT_EXCEEDED
            // LIMIT_EXCEEDED (generator#102, limit mode only): a configured
            // receiver-side cap on a schema-unbounded field. A policy rejection
            // distinct from INVALID — its own verdict `L`, not `R`. Guarded by the
            // build macro: only the pure-C++ corelib's Error carries LimitExceeded
            // (the c-cpp fixed-capacity wrapper's Error does not).
            if (r.code() == sofab::Error::LimitExceeded)
            {
                std::fputs("L\n", out);
                return;
            }
#endif
            std::fprintf(out, "R %s\n", reject_class(r.code()));
            return;
        }
        // try_decode already wrote the decoded value into `m` on ok().
    }

    // Accept. In materialize mode (oracle/materialized.md) dump the decoded value
    // field-by-field instead of re-encoding it to wire.
    static int materialize = -1;
    if (materialize < 0) materialize = std::getenv("SOFAB_MATERIALIZE") ? 1 : 0;
    if (materialize)
    {
        // GENERATED walker (materialize_gen.inc): dump the decoded value
        // field-by-field. Output is all ASCII (hex/digits/punctuation, no NUL), so
        // writing the std::string as a C string is safe.
        std::string dump = ::materialize(m);
        std::fputs("A ", out);
        std::fwrite(dump.data(), 1, dump.size(), out);
        std::fputc('\n', out);
        return;
    }

    // Accept: re-encode the decoded value and emit its canonical wire as hex.
    std::vector<std::uint8_t> enc = m.encode();
    std::fputs("A ", out);
    for (std::uint8_t b : enc)
    {
        std::fprintf(out, "%02x", b);
    }
    std::fputc('\n', out);
}

int main()
{
    std::vector<std::uint8_t> buf;
    for (;;)
    {
        std::uint8_t lenbytes[4];
        std::size_t got = std::fread(lenbytes, 1, 4, stdin);
        if (got == 0) break; // clean EOF at record boundary
        if (got != 4) { std::fprintf(stderr, "crucible-cpp: short length prefix\n"); return 1; }

        std::uint32_t n = (std::uint32_t)lenbytes[0] | ((std::uint32_t)lenbytes[1] << 8) |
                          ((std::uint32_t)lenbytes[2] << 16) | ((std::uint32_t)lenbytes[3] << 24);

        buf.resize(n);
        if (n > 0 && std::fread(buf.data(), 1, n, stdin) != n)
        {
            std::fprintf(stderr, "crucible-cpp: short payload\n");
            return 1;
        }

        decode_and_report(buf.data(), n, stdout);
        std::fflush(stdout);
    }
    return 0;
}
