// Crucible C++ driver — shared body for BOTH C++ corelibs:
//   cpp    -> corelib-cpp        (pure C++20, header-only)
//   c-cpp  -> corelib-c-cpp      (the C++ wrapper over the C corelib)
//
// build.sh selects which `sofab/sofab.hpp` is on the include path; the generated
// probe.hpp and the sofab:: API (IStreamObject, Result, Error) are identical
// across both, so this one source builds against either.
//
// Single pass, through the GENERATED decode entry. Normal mode goes via
// message::Probe::try_decode, which — unlike a bare IStreamObject::feed — installs the
// §5.2 measure-phase schema (setSchema) that rejects an over-count / over-maxlen /
// over-index field at its deciding word, so a field that is BOTH over-bound and
// truncated is INVALID, not INCOMPLETE (F-0032). Both return the Result (verdict) and
// fill the value in one call. Limit mode (CRUCIBLE_LIMIT_MODE, the unbounded probe-dyn
// schema) has no §5.2 schema bounds, so it uses a bare feed there: the generated
// try_decode additionally wires Limits{SOFAB_MAX_DYN_BUFFERED_FIELD}, a *byte*-size
// reassembly cap sofabgen derives from the element caps (too small — an 8-element array
// is ~10 B), which would spuriously LimitExceed a valid at-cap array. The receiver-side
// element/length caps are enforced by the generated deserialize either way.
//
// Emits the canonical form (oracle/canonical.md) over the replay protocol
// (drivers/common/CONTRACT.md).
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <span>
#include <string>
#include <utility>
#include <vector>

#include "probe.hpp" // generated; pulls the variant's sofab/sofab.hpp

// Materialized-value walker (oracle/materialized.md), SOFAB_MATERIALIZE=1. GENERATED
// at build time from the schema descriptor by materialize_gen.py (build.sh runs it
// before this compile); a schema change regenerates it with zero hand-editing. It
// provides `std::string materialize(const message::Probe&)`, unrolled straight-line
// member-access code written against ONLY the member API shared by both corelib
// variants (std::string/std::vector/std::array vs FixedString/FixedBytes/InlineVector),
// so this one source stays variant-agnostic. See materialize_gen.py.
#include "materialize_gen.inc" // generated by build.sh -> gen/$VARIANT/

static const char *reject_class(sofab::Error e)
{
    switch (e)
    {
        case sofab::Error::InvalidMessage:  return "invalid_msg";
        case sofab::Error::InvalidArgument: return "argument";
        // Error::UsageError was removed in corelib-cpp#54; the canonical "usage"
        // class stays in oracle/canonical.md for the corelibs that still have it.
        // Anything unmapped falls through to "other".
        case sofab::Error::BufferFull:      return "buffer_full";
        default:                            return "other";
    }
}

// ---- the streaming axes (drivers/common/CONTRACT.md, "The streaming axes") ------
//
// The replay protocol hands each record over whole and re-encodes it with one call, so
// the generated API's streaming surfaces are unreachable through it. Five environment
// variables open them; unset, every one of them is today's behaviour byte for byte.
//
// C++ is the one backend with **no generated `decoder()`** (crucible#132): chunked
// decode is driven by hand. That is not a workaround here — `try_decode` is itself just
// an `IStreamInline` bound to `deserialize` plus a single `feed`, so feeding the same
// stream in pieces is the identical construction with the identical schema handling.
// Anything else (a bare `IStreamObject`, say) would decode under different rules and
// report a chunk-invariance failure that was really a try_decode-vs-feed difference.
struct StreamCfg
{
    long split = 0;                            // SOFAB_SPLIT=k  — two chunks at k
    long chunk = 0;                            // SOFAB_CHUNK=n  — fixed-size chunks
    bool scrub = false;                        // SOFAB_CHUNK_SCRUB=1
    enum Enc { EncNew, EncTo, EncStream } enc = EncNew;  // SOFAB_ENCODE
    long flush = 0;                            // SOFAB_FLUSH=n  — OStream buffer size
};

static StreamCfg g_cfg;

static long env_long(const char *name)
{
    const char *v = std::getenv(name);
    if (!v || !*v) return 0;
    return std::strtol(v, nullptr, 10);
}

// Read once at startup. An unknown SOFAB_ENCODE value is a hard error rather than a
// fallback: reporting a mode as passing that never ran is the one failure the encode
// gate exists to prevent, so the driver must never quietly substitute another surface.
static void read_stream_cfg()
{
    g_cfg.split = env_long("SOFAB_SPLIT");
    g_cfg.chunk = env_long("SOFAB_CHUNK");
    g_cfg.flush = env_long("SOFAB_FLUSH");
    const char *s = std::getenv("SOFAB_CHUNK_SCRUB");
    g_cfg.scrub = s && *s && std::strcmp(s, "0") != 0;
    const char *e = std::getenv("SOFAB_ENCODE");
    if (!e || !*e || std::strcmp(e, "new") == 0)       g_cfg.enc = StreamCfg::EncNew;
    else if (std::strcmp(e, "to") == 0)                g_cfg.enc = StreamCfg::EncTo;
    else if (std::strcmp(e, "stream") == 0)            g_cfg.enc = StreamCfg::EncStream;
    else
    {
        std::fprintf(stderr, "crucible-cpp: unknown SOFAB_ENCODE=%s "
                             "(this backend has new, to, stream)\n", e);
        std::exit(2);
    }

    // Announce the configuration on stderr (never parsed — CONTRACT.md). Without this
    // a driver that silently ignored the variables would be indistinguishable from one
    // that honours them: identical stdout either way. That is the vacuous pass the
    // opt-in roster guards against at the gate level; this is the same guard at the
    // driver level, and it is what makes "this driver really re-feeds" checkable
    // rather than asserted.
    if (g_cfg.split || g_cfg.chunk || g_cfg.scrub || g_cfg.flush ||
        g_cfg.enc != StreamCfg::EncNew)
    {
        std::fprintf(stderr,
                     "crucible-cpp: streaming cfg split=%ld chunk=%ld scrub=%d "
                     "enc=%s flush=%ld\n",
                     g_cfg.split, g_cfg.chunk, g_cfg.scrub ? 1 : 0,
                     g_cfg.enc == StreamCfg::EncNew ? "new"
                         : g_cfg.enc == StreamCfg::EncTo ? "to" : "stream",
                     g_cfg.flush);
    }
}

// How the record is cut on its way into the decoder. Never an empty chunk: k<=0,
// k>=len and n>=len all mean one chunk holding the whole record, which is exactly
// today's single feed. A zero-length record yields no chunks at all — the caller
// treats it as the valid all-defaults message and does not feed it (corelib-c-cpp
// asserts datalen>0).
static std::vector<std::pair<std::size_t, std::size_t>> slices(std::size_t len)
{
    std::vector<std::pair<std::size_t, std::size_t>> out;
    if (len == 0) return out;
    if (g_cfg.chunk > 0)
    {
        std::size_t n = static_cast<std::size_t>(g_cfg.chunk);
        for (std::size_t o = 0; o < len; o += n)
            out.emplace_back(o, std::min(n, len - o));
        return out;
    }
    if (g_cfg.split > 0 && static_cast<std::size_t>(g_cfg.split) < len)
    {
        std::size_t k = static_cast<std::size_t>(g_cfg.split);
        out.emplace_back(0, k);
        out.emplace_back(k, len - k);
        return out;
    }
    out.emplace_back(0, len);
    return out;
}

// Feed `data` in the configured pieces through ONE stream, exactly as try_decode does
// with one piece. The verdict is the last feed's Result — C++ has no `finish()`, so
// this Result *is* the status the contract requires the verdict to come from. An error
// that is not `incomplete` is terminal and stops the feeding, per the contract.
//
// SOFAB_CHUNK_SCRUB copies each piece into a buffer the driver owns, feeds that, and
// overwrites it with 0xA5 once `feed` returns. A decoder that borrowed from the chunk
// rather than copying out of it then reads back the scrub pattern.
static sofab::IStreamImpl::Result decode_streamed(const std::uint8_t *data,
                                                  std::size_t len,
                                                  message::Probe &m)
{
    m.reset();
    sofab::IStreamInline *isp = nullptr;
    sofab::IStreamInline is{[&m, &isp](sofab::id id, std::size_t size, std::size_t count) {
        m.deserialize(*isp, id, size, count);
    }};
    isp = &is;

    std::vector<std::uint8_t> scratch;
    sofab::IStreamImpl::Result r = is.feed(data, 0);  // placeholder; overwritten below
    for (auto [off, n] : slices(len))
    {
        if (g_cfg.scrub)
        {
            scratch.assign(data + off, data + off + n);
            r = is.feed(scratch.data(), n);
            std::memset(scratch.data(), 0xA5, n);
        }
        else
        {
            r = is.feed(data + off, n);
        }
        if (!r.ok() && !r.incomplete()) break;   // INVALID is terminal
    }
    return r;
}

// Which generated call produces the `A <hex>` payload. All three must emit identical
// bytes for one decoded value — the family is byte-canonical — and SOFAB_FLUSH must not
// change that either: it hands the OStream an n-byte buffer, so the sink receives the
// message in n-byte pieces and the encoder crosses a buffer boundary at every offset.
static std::vector<std::uint8_t> encode_via(const message::Probe &m)
{
    if (g_cfg.enc == StreamCfg::EncNew)
    {
        return m.encode();
    }
    if (g_cfg.enc == StreamCfg::EncTo)
    {
        std::vector<std::uint8_t> buf(message::Probe::_maxSize);
        std::size_t used = m.encodeTo(buf.data(), buf.size());
        buf.resize(used);
        return buf;
    }
    // stream: serialize into an OStream, collecting what it flushes.
    std::vector<std::uint8_t> out;
    std::size_t cap = g_cfg.flush > 0 ? static_cast<std::size_t>(g_cfg.flush)
                                      : message::Probe::_maxSize;
    if (cap == 0) cap = 1;
    std::shared_ptr<std::uint8_t[]> buf(new std::uint8_t[cap]);
    {
        sofab::OStream os{[&out](std::span<const std::uint8_t> s) {
                              out.insert(out.end(), s.begin(), s.end());
                          },
                          buf, cap};
        (void)m.serialize(os);
        os.flush();   // hand over whatever is still buffered
    }
    return out;
}

static void decode_and_report(const std::uint8_t *data, std::size_t len, FILE *out)
{
    message::Probe m; // schema defaults

    // An empty buffer is the valid all-defaults message. The c-cpp wrapper routes
    // to the C istream, which asserts datalen>0 as a debug precondition (see the C
    // driver / docs/ARCHITECTURE.md), so skip feed for len==0 as the C driver does.
    if (len > 0)
    {
#ifdef CRUCIBLE_LIMIT_MODE
        // Unbounded probe-dyn schema: no §5.2 bounds to measure, and try_decode's
        // byte-size buffered cap would spuriously reject a valid at-cap array. Bare
        // feed; the generated deserialize still enforces the element/length caps.
        sofab::IStreamObject<message::Probe> in;
        auto r = in.feed(data, len);
#else
        // decode_streamed is try_decode's own construction — an IStreamInline bound to
        // `deserialize` — fed in the pieces SOFAB_SPLIT / SOFAB_CHUNK ask for. With
        // none of them set that is a single feed, i.e. try_decode exactly.
        auto r = decode_streamed(data, len, m);
#endif
        if (r.incomplete())
        {
            // INCOMPLETE (MESSAGE_SPEC §7): bytes end mid-message — the third
            // canonical verdict, neither accept (A) nor reject (R). Not an error.
            std::fputs("I\n", out);
            return;
        }
        if (!r.ok())
        {
#ifdef CRUCIBLE_HAS_LIMIT_EXCEEDED
            // LIMIT_EXCEEDED (generator#102, limit mode only): a configured
            // receiver-side cap on a schema-unbounded field. A policy rejection
            // distinct from INVALID — its own verdict `L`, not `R`. Guarded by the
            // build macro: only the pure-C++ corelib's Error carries LimitExceeded
            // (the c-cpp fixed-capacity wrapper's Error does not).
            if (r.code() == sofab::Error::LimitExceeded)
            {
                std::fputs("L\n", out);
                return;
            }
#endif
            std::fprintf(out, "R %s\n", reject_class(r.code()));
            return;
        }
#ifdef CRUCIBLE_LIMIT_MODE
        m = *in;
#else
        // try_decode already wrote the decoded value into `m` on ok().
#endif
    }

    // Accept. In materialize mode (oracle/materialized.md) dump the decoded value
    // field-by-field instead of re-encoding it to wire.
    static int materialize = -1;
    if (materialize < 0) materialize = std::getenv("SOFAB_MATERIALIZE") ? 1 : 0;
    if (materialize)
    {
        // GENERATED walker (materialize_gen.inc): dump the decoded value
        // field-by-field. Output is all ASCII (hex/digits/punctuation, no NUL), so
        // writing the std::string as a C string is safe.
        std::string dump = ::materialize(m);
        std::fputs("A ", out);
        std::fwrite(dump.data(), 1, dump.size(), out);
        std::fputc('\n', out);
        return;
    }

    // Accept: re-encode the decoded value and emit its canonical wire as hex, through
    // whichever encode surface SOFAB_ENCODE selects (default: the allocating encode()).
    std::vector<std::uint8_t> enc = encode_via(m);
    std::fputs("A ", out);
    for (std::uint8_t b : enc)
    {
        std::fprintf(out, "%02x", b);
    }
    std::fputc('\n', out);
}

int main()
{
    read_stream_cfg();
    std::vector<std::uint8_t> buf;
    for (;;)
    {
        std::uint8_t lenbytes[4];
        std::size_t got = std::fread(lenbytes, 1, 4, stdin);
        if (got == 0) break; // clean EOF at record boundary
        if (got != 4) { std::fprintf(stderr, "crucible-cpp: short length prefix\n"); return 1; }

        std::uint32_t n = (std::uint32_t)lenbytes[0] | ((std::uint32_t)lenbytes[1] << 8) |
                          ((std::uint32_t)lenbytes[2] << 16) | ((std::uint32_t)lenbytes[3] << 24);

        buf.resize(n);
        if (n > 0 && std::fread(buf.data(), 1, n, stdin) != n)
        {
            std::fprintf(stderr, "crucible-cpp: short payload\n");
            return 1;
        }

        decode_and_report(buf.data(), n, stdout);
        std::fflush(stdout);
    }
    return 0;
}
