#!/usr/bin/env python3
"""Build-time generator for the C++ materialized-value walker (oracle/materialized.md).

C++ has no runtime reflection, so the walker over the decoded `message::Probe` is
UNROLLED from the schema descriptor into straight-line member-access code at build
time. A schema change regenerates the descriptor (engine/structured/schema.py ->
oracle/materialized-schema.json) and this emits a fresh walker with zero hand-editing.

Emits a `materialize_gen.inc` implementing:

    std::string materialize(const message::Probe& m);

which walks the decoded value per the grammar and returns the materialized-form dump
(no "A " prefix), byte-for-byte equal to engine/structured/materialize.py.

The SAME driver.cpp compiles for BOTH corelib variants (cpp = std::string/std::vector
/std::array, c-cpp = FixedString/FixedBytes/InlineVector), so the generated code uses
ONLY the member API both share: `.size()`, `operator[]`, `.data()` for string/blob;
`std::array<T,N>` iteration for numeric. Nothing here is variant-specific.

Descriptor: `{ "message": ..., "fields": [node, ...] }`; node has `id`, `name`,
`kind`. Kinds: leaf `u|s|fp32|fp64|string|blob`; `struct` (+`fields`); `array`
(+`elem` u|s|fp32|fp64, +`count`); `wrapper` (+`elem` string|blob, +`count`). The
C++ member name for each node is its schema `name` (confirmed against both
drivers/cpp/gen/{cpp,c-cpp}/probe.hpp); paths join with `.`.

Usage:
    materialize_gen.py [OUT.inc]
      OUT.inc   output path (default: stdout)
    Descriptor path: $SOFAB_MATERIALIZE_SCHEMA, else <repo-root>/oracle/materialized-schema.json
"""
import json
import os
import sys


def _load_descriptor():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(here, "..", ".."))
    path = os.environ.get("SOFAB_MATERIALIZE_SCHEMA") or os.path.join(
        root, "oracle", "materialized-schema.json"
    )
    with open(path, "r") as f:
        return json.load(f), path


# --- leaf emitters: append one materialized leaf for a member-access expr `acc` ---
def _leaf(kind, acc):
    if kind == "u":      return f"_md_u(o, {acc});"
    if kind == "s":      return f"_md_s(o, {acc});"
    if kind == "fp32":   return f"_md_f32(o, {acc});"
    if kind == "fp64":   return f"_md_f64(o, {acc});"
    if kind == "string": return f"_md_str(o, {acc});"
    if kind == "blob":   return f"_md_blob(o, {acc});"
    raise ValueError(f"not a leaf kind: {kind!r}")


def _emit(node, acc, out, ind, depth):
    """Append C++ statements that materialize `node` (member-access expr `acc`)."""
    pad = "    " * ind
    kind = node["kind"]

    if kind in ("u", "s", "fp32", "fp64", "string", "blob"):
        out.append(pad + _leaf(kind, acc))
        return

    if kind == "struct":
        out.append(pad + "o.push_back('{');")
        for i, f in enumerate(node["fields"]):
            sep = "" if i == 0 else ";"
            out.append(pad + f'o += "{sep}{f["id"]}:";')
            _emit(f, f"{acc}.{f['name']}", out, ind, depth)
        out.append(pad + "o.push_back('}');")
        return

    if kind in ("array", "wrapper"):
        # Both are fixed-count containers exposing .size()/operator[]. Numeric/fp
        # arrays are std::array<T,N> (always N elements); wrapper arrays are the
        # dynamic container (its length is itself the signal). Same walk for both:
        # emit every in-memory element in index order.
        iv = f"_i{depth}"
        out.append(pad + "o.push_back('[');")
        out.append(pad + f"for (std::size_t {iv} = 0; {iv} < {acc}.size(); ++{iv}) {{")
        out.append(pad + f"    if ({iv}) o.push_back(',');")
        _emit_elem(node["elem"], f"{acc}[{iv}]", out, ind + 1, depth + 1)
        out.append(pad + "}")
        out.append(pad + "o.push_back(']');")
        return

    raise ValueError(f"unhandled kind {kind!r}")


def _emit_elem(elem, acc, out, ind, depth):
    pad = "    " * ind
    # array elem: u|s|fp32|fp64 ; wrapper elem: string|blob — all leaves.
    out.append(pad + _leaf(elem, acc))


_PRELUDE = r"""// Code generated by drivers/cpp/materialize_gen.py from the schema descriptor.
// DO NOT EDIT. Regenerated by build.sh on every build.
//
// Straight-line, schema-agnostic materialized-value walker (oracle/materialized.md):
// C++ has no runtime reflection, so the descriptor is UNROLLED into explicit
// member-access code. Written against ONLY the member API shared by both corelib
// variants (cpp: std::string/std::vector/std::array; c-cpp: FixedString/FixedBytes/
// InlineVector): .size(), operator[], .data() for string/blob; std::array for numeric.
// Output equals engine/structured/materialize.py byte-for-byte on a COMPLETE decode.
#include <array>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <string>

namespace {

inline void _md_hex(std::string &o, const void *pv, std::size_t n) {
    static const char H[] = "0123456789abcdef";
    const unsigned char *p = static_cast<const unsigned char *>(pv);
    for (std::size_t i = 0; i < n; ++i) {
        o.push_back(H[p[i] >> 4]);
        o.push_back(H[p[i] & 0x0f]);
    }
}
// u8/i8 widen to a wide int so they print as a number, not a character.
inline void _md_u(std::string &o, unsigned long long v) {
    char b[24];
    int n = std::snprintf(b, sizeof b, "u%llu", v);
    o.append(b, static_cast<std::size_t>(n));
}
inline void _md_s(std::string &o, long long v) {
    char b[24];
    int n = std::snprintf(b, sizeof b, "s%lld", v);
    o.append(b, static_cast<std::size_t>(n));
}
inline void _md_f32(std::string &o, float x) {
    std::uint32_t bits;
    std::memcpy(&bits, &x, 4);
    char b[16];
    int n = std::snprintf(b, sizeof b, "f%08x", bits);
    o.append(b, static_cast<std::size_t>(n));
}
inline void _md_f64(std::string &o, double x) {
    std::uint64_t bits;
    std::memcpy(&bits, &x, 8);
    char b[24];
    int n = std::snprintf(b, sizeof b, "F%016llx", static_cast<unsigned long long>(bits));
    o.append(b, static_cast<std::size_t>(n));
}
// string: "t" + byte-length + ":" + UTF-8 bytes as hex (std::string / FixedString).
template <typename S>
inline void _md_str(std::string &o, const S &s) {
    std::size_t n = s.size();
    char b[24];
    int k = std::snprintf(b, sizeof b, "t%zu:", n);
    o.append(b, static_cast<std::size_t>(k));
    _md_hex(o, s.data(), n);
}
// blob: "b" + length + ":" + bytes as hex (std::vector<uint8_t> / FixedBytes).
template <typename B>
inline void _md_blob(std::string &o, const B &b) {
    std::size_t n = b.size();
    char t[24];
    int k = std::snprintf(t, sizeof t, "b%zu:", n);
    o.append(t, static_cast<std::size_t>(k));
    _md_hex(o, b.data(), n);
}

} // namespace
"""


def generate(desc):
    body = []
    body.append("std::string materialize(const message::Probe &m) {")
    body.append("    std::string o;")
    body.append("    o.push_back('{');")
    for i, f in enumerate(desc["fields"]):
        sep = "" if i == 0 else ";"
        body.append(f'    o += "{sep}{f["id"]}:";')
        _emit(f, f"m.{f['name']}", body, 1, 0)
    body.append("    o.push_back('}');")
    body.append("    return o;")
    body.append("}")
    return _PRELUDE + "\n" + "\n".join(body) + "\n"


def main():
    desc, _path = _load_descriptor()
    src = generate(desc)
    if len(sys.argv) >= 2 and sys.argv[1] != "-":
        with open(sys.argv[1], "w") as f:
            f.write(src)
    else:
        sys.stdout.write(src)


if __name__ == "__main__":
    main()
