#!/usr/bin/env sh
# Crucible deep union suite -- the union shapes scripts/run-union.sh cannot reach.
#
# schema/probe-union.sofab.yaml has five leaf options and one default_id; this one adds a
# struct option with a non-zero member default, an empty struct option, array options,
# enum/fp32 options with non-zero defaults, a struct default_id, a union of union, an array of
# unions, non-contiguous option ids and a union inside a struct (see the schema header).
#
# Four passes over the same schema and the same corpus/union-deep (generated by
# engine/structured/sweep_union_deep.py, which also owns the expectation of every vector):
#   1. differential   -- do the 17 drivers agree (run.sh)
#   2. conformance    -- does the agreed answer match the spec (sweep_run.py --union-deep):
#                        identity / same: / reject / not_reject per vector
#   3. chunk          -- decode is invariant under any chunking (run-chunked.sh)
#   4. encode         -- every encode surface writes the same bytes (run-encode.sh)
#
#   ./scripts/run-union-deep.sh             # all four
#   ./scripts/run-union-deep.sh --quick     # passes 1 and 2 only (one driver build)
set -u
ROOT=$(cd "$(dirname "$0")/.." && pwd)
export SCHEMA="$ROOT/schema/probe-union-deep.sofab.yaml"
QUICK=0
[ "${1:-}" = "--quick" ] && QUICK=1
rc=0

echo "==> [union-deep] regenerating corpus/union-deep" >&2
python3 "$ROOT/engine/structured/sweep_union_deep.py" "$ROOT/corpus/union-deep" >&2 || exit 1

echo "==> [union-deep] 1/4 differential" >&2
CORPUS="$ROOT/corpus/union-deep" "$ROOT/scripts/run.sh" || rc=1

echo "==> [union-deep] 2/4 conformance (identity / same: / reject / not_reject)" >&2
python3 "$ROOT/engine/structured/sweep_run.py" --union-deep || rc=1

if [ "$QUICK" = "0" ]; then
    echo "==> [union-deep] 3/4 chunk invariance" >&2
    CORPUS="$ROOT/corpus/union-deep" "$ROOT/scripts/run-chunked.sh" --modes chunk || rc=1
    echo "==> [union-deep] 4/4 encode invariance" >&2
    CORPUS="$ROOT/corpus/union-deep" "$ROOT/scripts/run-encode.sh" || rc=1
fi

echo "==> [union-deep] restoring probe binaries" >&2
SCHEMA="$ROOT/schema/probe.sofab.yaml" CORPUS="$ROOT/corpus/seeds" "$ROOT/scripts/run.sh" >/dev/null || true
exit $rc
