#!/usr/bin/env python3
"""Build-time generator for the Crucible Rust driver's materialized-value walker.

Rust has no runtime reflection, so the SOFAB_MATERIALIZE walker cannot be a runtime
table driven off the schema descriptor — it must be straight-line source. This script
reads the schema descriptor (oracle/materialized-schema.json, produced by
engine/structured/schema.py) and EMITS a Rust source file that implements

    pub fn materialize(m: &Probe) -> String

by UNROLLING the descriptor into explicit field-access code: struct -> recurse the
access path (`m.nested.f32`), array -> loop the `[T;count]`, wrapper -> loop the
container. The Rust field names are the schema names verbatim.

The emitted source is included into the driver (build.sh drops it next to main.rs and
driver.rs `include!`s it), so a schema change regenerates the walker with zero hand
edits. It builds under BOTH corelib variants (std / no_std): it touches only member
APIs both container flavors share (`.as_bytes()`, slice deref `&x[..]`, `.iter()`),
and builds its output via `String` + `core::fmt::Write` (the driver binary is std for
both variants, so `String` is always available).

Leaf formatting (matches oracle/materialized.md / engine/structured/materialize.py):
  fp32   f{:08x} of f32::to_bits()      unsigned  u{}
  fp64   F{:016x} of f64::to_bits()     signed    s{}
  string t{len}:{hex} of .as_bytes()    blob      b{len}:{hex} of &x[..]

Usage:
    materialize_gen.py [OUT.rs]        # write to OUT.rs (or stdout if omitted)

The descriptor path is os.environ["SOFAB_MATERIALIZE_SCHEMA"] if set, else
<repo>/oracle/materialized-schema.json (repo root resolved from this script's path).
"""
import json
import os
import sys

_HELPERS = r'''// GENERATED by drivers/rust/materialize_gen.py from oracle/materialized-schema.json.
// Do not edit by hand — a schema change regenerates this file at build time.
//
// Straight-line materialized-value walker (oracle/materialized.md). Included into the
// driver via `include!`, compiled for both corelib variants. Only member APIs shared
// by the std and no_std container flavors are used, and output is built with
// `core::fmt::Write` into a `String` (the driver binary is std for both variants).

fn mz_hex(out: &mut String, b: &[u8]) {
    use core::fmt::Write as _;
    for x in b {
        let _ = write!(out, "{:02x}", x);
    }
}
fn mz_text(out: &mut String, b: &[u8]) {
    use core::fmt::Write as _;
    let _ = write!(out, "t{}:", b.len());
    mz_hex(out, b);
}
fn mz_blob(out: &mut String, b: &[u8]) {
    use core::fmt::Write as _;
    let _ = write!(out, "b{}:", b.len());
    mz_hex(out, b);
}
fn mz_arr_u<T: core::fmt::Display>(out: &mut String, a: &[T]) {
    use core::fmt::Write as _;
    let _ = write!(out, "[");
    for (i, v) in a.iter().enumerate() {
        let _ = write!(out, "{}u{}", if i > 0 { "," } else { "" }, v);
    }
    let _ = write!(out, "]");
}
fn mz_arr_s<T: core::fmt::Display>(out: &mut String, a: &[T]) {
    use core::fmt::Write as _;
    let _ = write!(out, "[");
    for (i, v) in a.iter().enumerate() {
        let _ = write!(out, "{}s{}", if i > 0 { "," } else { "" }, v);
    }
    let _ = write!(out, "]");
}
fn mz_arr_f32(out: &mut String, a: &[f32]) {
    use core::fmt::Write as _;
    let _ = write!(out, "[");
    for (i, v) in a.iter().enumerate() {
        let _ = write!(out, "{}f{:08x}", if i > 0 { "," } else { "" }, v.to_bits());
    }
    let _ = write!(out, "]");
}
fn mz_arr_f64(out: &mut String, a: &[f64]) {
    use core::fmt::Write as _;
    let _ = write!(out, "[");
    for (i, v) in a.iter().enumerate() {
        let _ = write!(out, "{}F{:016x}", if i > 0 { "," } else { "" }, v.to_bits());
    }
    let _ = write!(out, "]");
}
'''

_ARR_FN = {"u": "mz_arr_u", "s": "mz_arr_s", "fp32": "mz_arr_f32", "fp64": "mz_arr_f64"}


def emit_value(node, path, out):
    """Append Rust statements that write the VALUE at access-path `path` (no id prefix)."""
    kind = node["kind"]
    if kind == "u":
        out.append('    let _ = write!(s, "u{}", ' + path + ');')
    elif kind == "s":
        out.append('    let _ = write!(s, "s{}", ' + path + ');')
    elif kind == "fp32":
        out.append('    let _ = write!(s, "f{:08x}", ' + path + '.to_bits());')
    elif kind == "fp64":
        out.append('    let _ = write!(s, "F{:016x}", ' + path + '.to_bits());')
    elif kind == "string":
        out.append('    mz_text(s, ' + path + '.as_bytes());')
    elif kind == "blob":
        out.append('    mz_blob(s, &' + path + '[..]);')
    elif kind == "struct":
        out.append('    let _ = write!(s, "{{");')
        for j, f in enumerate(node["fields"]):
            if j > 0:
                out.append('    let _ = write!(s, ";");')
            out.append('    let _ = write!(s, "' + str(f["id"]) + ':");')
            emit_value(f, path + "." + f["name"], out)
        out.append('    let _ = write!(s, "}}");')
    elif kind == "array":
        out.append("    " + _ARR_FN[node["elem"]] + "(s, &" + path + "[..]);")
    elif kind == "wrapper":
        leaf = "mz_text(s, x.as_bytes());" if node["elem"] == "string" else "mz_blob(s, &x[..]);"
        out.append('    let _ = write!(s, "[");')
        out.append("    for (i, x) in " + path + ".iter().enumerate() {")
        out.append('        if i > 0 { let _ = write!(s, ","); }')
        out.append("        " + leaf)
        out.append("    }")
        out.append('    let _ = write!(s, "]");')
    else:
        raise ValueError("unhandled kind %r" % kind)


def generate(desc):
    # The message itself is an obj (struct) whose fields hang off `m`.
    msg_node = {"kind": "struct", "fields": desc["fields"]}
    body = []
    emit_value(msg_node, "m", body)
    lines = [
        _HELPERS,
        "",
        "pub fn materialize(m: &Probe) -> String {",
        "    use core::fmt::Write as _;",
        "    let mut s = String::new();",
        "    let s = &mut s;",
    ]
    lines += body
    lines += [
        "    core::mem::take(s)",
        "}",
        "",
    ]
    return "\n".join(lines)


# When the driver is built against a NON-default schema (the union suite's
# probe-union, limit mode's probe-dyn), the materialized oracle does not apply — its
# reference is probe-only and materialize mode is never enabled there. The walker only
# needs to COMPILE (dead code), so emit a stub for the mismatched Probe shape instead
# of a walker that references the default probe's fields.
_STUB = ("// GENERATED stub — this schema is not the materialized oracle's probe.\n"
         "#[allow(dead_code)]\n"
         "pub fn materialize(_m: &Probe) -> String { String::new() }\n")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.abspath(os.path.join(here, "..", ".."))
    built = sys.argv[2] if len(sys.argv) >= 3 else None
    if built and os.path.basename(built) != "probe.sofab.yaml":
        src = _STUB
        if len(sys.argv) >= 2:
            with open(sys.argv[1], "w") as f:
                f.write(src)
        else:
            sys.stdout.write(src)
        return
    schema = os.environ.get("SOFAB_MATERIALIZE_SCHEMA") or os.path.join(
        root, "oracle", "materialized-schema.json"
    )
    with open(schema) as f:
        desc = json.load(f)
    src = generate(desc)
    if len(sys.argv) >= 2:
        with open(sys.argv[1], "w") as f:
            f.write(src)
    else:
        sys.stdout.write(src)


if __name__ == "__main__":
    main()
